CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'secret'; 
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION; 
CREATE USER 'walg_exporter'@'%' IDENTIFIED BY 'secret!';
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'walg_exporter'@'%';
GRANT SELECT ON performance_schema.* TO 'walg_exporter'@'%';
FLUSH PRIVILEGES; 

CREATE DATABASE IF NOT EXISTS demo;
USE demo; 
CREATE TABLE IF NOT EXISTS t(id INT PRIMARY KEY AUTO_INCREMENT, note VARCHAR(100)); 
INSERT INTO t(note) VALUES('init1'),('init2') ON DUPLICATE KEY UPDATE note=VALUES(note);
